services: 
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development   
      - ASPNETCORE_URLS=http://*:5000
    networks:
      - warehouse-network
  postgres:
    image: postgres:16
    container_name: warehouse-postgres
    environment:
      POSTGRES_DB: warehouse_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - warehouse-network

  redis:
    image: redis:7.2
    container_name: warehouse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - warehouse-network

volumes:
  postgres-data:
  redis-data:

networks:
  warehouse-network:
    driver: bridge